---
AWSTemplateFormatVersion: '2010-09-09'

Description: Bedrock Knowledge Base and OpenSearch Collection

Parameters:
  KnowledgeBucket:
    Type: String
    Description: S3 bucket name containing knowledge base content
  
  BedrockRoleArn:
    Type: String
    Description: ARN of the Bedrock KB role

  EmbeddingModelArn:
    Type: String
    Description: ARN of the embedding model

  VectorIndexName:
    Type: String
    Description: Name of the vector index
    Default: "mykbvectorindex"
  
  VectorCollectionArn:
    Type: String
    Description: ARN of the OpenSearch Collection

  MetadataFieldName:
    Type: String
    Description: Name of the metadata field
    Default: "metadata"
  
  VectorFieldName:
    Type: String
    Description: Name of the embedding vector field
    Default: "vector"

  TextFieldName:
    Type: String
    Description: Name of the text field
    Default: "chunk"

Outputs:
  KnowledgeBase:
    Description: Id of the Bedrock Knowledge Base
    Value: !Ref KnowledgeBase

  DataSource:
    Description: Id of the Bedrock DataSource
    Value: !GetAtt DataSource.DataSourceId

Resources:

  KnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub "${AWS::StackName}-knowledge-base"
      RoleArn: !Ref BedrockRoleArn
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Ref EmbeddingModelArn
      StorageConfiguration: 
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !Ref VectorCollectionArn
          VectorIndexName: !Ref VectorIndexName
          FieldMapping:
            MetadataField: !Ref MetadataFieldName
            VectorField: !Ref VectorFieldName
            TextField: !Ref TextFieldName
  
  DataSource:
    Type: AWS::Bedrock::DataSource
    Properties:
      Name: !Sub "${AWS::StackName}-DataSource"
      KnowledgeBaseId: !Ref KnowledgeBase
      DataSourceConfiguration: 
        Type: S3
        S3Configuration:
          BucketArn: !Sub "arn:aws:s3:::${KnowledgeBucket}"